# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest3',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest3',
                'lib_path': 'ntest3'},
  'syms': {'ntest3.core': {'ntest3.core.foo': ('core.html#foo', 'ntest3/core.py')}}}